### ISSUE TITLE
cannot find  active-model-adapter`  module

### ISSUE THREAD

**Issue by lessless** [ember-data/active-model-adapter#24] opened 2015-07-07 11:38 UTC
After installation there is an error that module is not found, but it does exist in the bower components folder:
```javascript 
import { ActiveModelSerializer } from 'active-model-adapter';
export default DS.ActiveModelSerializer.extend({..});
```

```javascript 
Error while processing route: welcome.address Could not find module `active-model-adapter` imported from `project/serializers/profile`
```

```bash
ls bower_components/active-model-adapter
LICENSE                 active-model-adapter.js
README.md               bower.json
```

**Comment by mswanson** [comment] 2015-07-07 19:17
@lessless try removing the DS. prefix from your export and see if it works.

```js
export default DS.ActiveModelSerializer.extend({..});
```

I am having the same issue. here is my code:

```js
import { ActiveModelAdapter } from 'active-model-adapter';
export default ActiveModelAdapter.extend({...});
```

ActiveModelAdapter: 1.13.3 
Ember Data: 1.13.4
Ember: 1.13.3
EmberCLI: 0.2.7

**Comment by mswanson** [comment] 2015-07-07 20:04
*UPDATE:* Inexplicably it started working. I removed the `node_modules` and `bower_components` directories and then cleared the cache for both, restarted ember serve and now things seem to be working.

**Comment by fivetanley** [comment] 2015-07-12 17:17
Glad it's working for you! Closing

**Comment by fivetanley** [comment] 2015-07-12 17:18
Ah, missed you're not the original issuer. Can you try running `rm -rf node_modules && bower cache clean && rm -rf bower_components &&  rm -rf node_modules && npm i && bower i` ?

**Comment by Eptis** [comment] 2015-07-13 08:27
Might be related to this I'm getting:
```
Error: Could not find module `active-model-adapter` imported from `app/initializers/active-model-adapter`
```
Ember-2.0.0-beta.2
Ember-Data 1.13.5
Ember CLI 1.13.1
ActiveModelAdapter 1.13.3

**Comment by tomster-strudel** [comment] 2015-07-13 12:45
Did you run ember install active-model-adapter?

**Comment by Eptis** [comment] 2015-07-13 12:46
Yes I have

**Comment by fivetanley** [comment] 2015-07-14 00:16
And the command above for clearing out node modules..?

**Comment by fivetanley** [comment] 2015-07-23 16:48
Closing due to inactivity. Feel free to reopen if 1.13.5 doesn't solve this for you.

**Comment by onezeno** [comment] 2015-07-29 15:54
Restarting Ember Server corrected this for me

**Comment by Eptis** [comment] 2015-08-10 08:15
This still isn't working for me. Tried the cache/removing all node modules and bower components and also restarting the app server.

**Comment by fivetanley** [comment] 2015-08-10 14:38
> I'm getting this message because of ember-cli-mirage

Do you know of a root cause? If we're playing badly with other plugins I'd like to fix that.

**Comment by Eptis** [comment] 2015-08-10 14:39
Haven't dived that far into it yet, I'm first updating my serializer to the new Serializer API. Will get back to it as soon as I finish that.

**Comment by maxkwallace** [comment] 2015-09-06 11:20
Does anyone know what the root cause of this issue is? I have one minimal acceptance test (just visiting a publicly-available route) that fails in PhantomJS with the error:
```
at http://localhost:7357/assets/test-support.js:6647: Could not find module 'active-model-adapter' imported from '[app name]/initializers/active-model-adapter'
```
The strangest thing is that it passes in Chrome when I run `ember test --server`.

**Comment by maxkwallace** [comment] 2015-09-17 14:49
To follow up on this, for me the root cause ended up being an incompatibility (ES5's Function.prototype.bind) between PhantomJS 1.9.x and `ember-cli-materialize`. Adding `ember-cli-es5-shim` fixed the issue. See (http://stackoverflow.com/questions/31640316/ember-cli-acceptance-tests-could-not-find-module/32437973#32437973)[here] for more links & detail.

**Comment by josemarluedke** [comment] 2015-09-26 03:37
I ran into the same problem, solved it by upgrading `ember-cli-shims` to `0.0.6`.

**Comment by wagenet** [comment] 2015-10-06 22:16
I'm pretty sure this issue happens when there's an error in the file prior to active-model-adapter getting loaded. I do not believe this is an active-model-adapter issue.

**Comment by maxkwallace** [comment] 2015-10-06 22:19
@wagenet yes, this is consistent with what I found. I saw similar errors caused by the same root cause (PhantomJS / ES5 incompatibility) that didn't involve `active-model-adapter`.

**Comment by fivetanley** [comment] 2015-10-07 04:46
Seems like unrelated to active-model-adapter. Closing.

**Closed by fivetanley** 2015-10-07 04:46 UTC

**Comment by fguillen** [comment] 2015-11-13 16:40
Same here.. as @onezeno said: "Restarting Ember Server corrected this for me"
